package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arrival generated by hbm2java
 */
@Entity
@Table(name = "arrivaldish",
         catalog = "default_db"
)
public class ArrivalDish implements java.io.Serializable {

    private Long idArrivalDish;
    private Date date;
    private BigDecimal sumInvoice;
    private String numberWaybill;
    private String note;
    private UserSwing userSwing;
    private Set arrivalDishLists = new HashSet(0);
    private Set caseRecord = new HashSet(0);

    public ArrivalDish() {
    }

    public ArrivalDish(Date date, BigDecimal sumInvoice) {
        this.date = date;
        this.sumInvoice = sumInvoice;
    }

    public ArrivalDish(UserSwing userSwing) {
        this.userSwing = userSwing;
    }
    
    public ArrivalDish(Date date, BigDecimal sumInvoice, BigDecimal sumArrival, String numberWaybill, String note, Set arrivalDishLists, UserSwing userSwing , Set caseRecord) {
        this.userSwing = userSwing;
        this.date = date;
        this.sumInvoice = sumInvoice;
        this.numberWaybill = numberWaybill;
        this.note = note;
        this.arrivalDishLists = arrivalDishLists;
        this.caseRecord = caseRecord;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_arrivaldish", unique = true, nullable = false)
    public Long getIdArrivalDish() {
        return this.idArrivalDish;
    }

    public void setIdArrivalDish(Long idArrivalDish) {
        this.idArrivalDish = idArrivalDish;
    }

    
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", nullable = false, length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "sumInvoice", nullable = false, precision = 9)
    public BigDecimal getSumInvoice() {
        return this.sumInvoice;
    }

    public void setSumInvoice(BigDecimal sumInvoice) {
        this.sumInvoice = sumInvoice;
    }

    @Column(name = "number_waybill", length = 100)
    public String getNumberWaybill() {
        return this.numberWaybill;
    }

    public void setNumberWaybill(String numberWaybill) {
        this.numberWaybill = numberWaybill;
    }

    @Column(name = "note", length = 500)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "arrivaldish")
    public Set getArrivalDishLists() {
        return this.arrivalDishLists;
    }

    public void setArrivalDishLists(Set arrivalDishLists) {
        this.arrivalDishLists = arrivalDishLists;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user", nullable = false)
    public UserSwing getUserSwing() {
        return this.userSwing;
    }

    public void setUserSwing(UserSwing userSwing) {
        this.userSwing = userSwing;
    }
    
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "caseRecord")
    public Set getCaseRecord() {
        return this.caseRecord;
    }

    public void setCaseRecord(Set caseRecord) {
        this.caseRecord = caseRecord;
    }
}
