package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArrivalList generated by hbm2java
 */
@Entity
@Table(name = "arrivaldishlist",
        catalog = "default_db"
)
public class ArrivalDishList implements java.io.Serializable {

    private Long idArrivalDishList;
    private ArrivalDish arrivalDish;
    private Dish dish;
    private BigDecimal amount;
    private BigDecimal priceOpt;

    public ArrivalDishList() {
    }

    public ArrivalDishList(ArrivalDish arrivalDish, Dish dish, BigDecimal amount, BigDecimal priceOpt) {
        this.arrivalDish = arrivalDish;
        this.dish = dish;
        this.amount = amount;
        this.priceOpt = priceOpt;

    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_arrivalDishList", unique = true, nullable = false)
    public Long getIdArrivalDishList() {
        return this.idArrivalDishList;
    }

    public void setIdArrivalDishList(Long idArrivalDishList) {
        this.idArrivalDishList = idArrivalDishList;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_arrivaldish", nullable = false)
    public ArrivalDish getArrivalDish() {
        return this.arrivalDish;
    }

    public void setArrivalDish(ArrivalDish arrivalDish) {
        this.arrivalDish = arrivalDish;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_dish", nullable = false)
    public Dish getDish() {
        return this.dish;
    }

    public void setDish(Dish dish) {
        this.dish = dish;
    }

    @Column(name = "amount", precision = 7, scale = 3)
    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Column(name = "priceOpt", precision = 7, scale = 2)
    public BigDecimal getPriceOpt() {
        return priceOpt;
    }

    public void setPriceOpt(BigDecimal priceOpt) {
        this.priceOpt = priceOpt;
    }

}
