package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CategoryGoods generated by hbm2java
 */
@Entity
@Table(name = "categorydish",
        catalog = "default_db"
)
public class CategoryDish implements java.io.Serializable {

    private Long idCategoryDish;
    private String name;
    private String note;

    public CategoryDish() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_categorydish", unique = true, nullable = false)
    public Long getIdCategoryDish() {
        return this.idCategoryDish;
    }

    public void setIdCategoryDish(Long idCategoryDish) {
        this.idCategoryDish = idCategoryDish;
    }

    @Column(name = "name", length = 1000)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "note", length = 1000)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    

}
