package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Pattern;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Discount generated by hbm2java
 */
@Entity
@Table(name = "discount",
        catalog = "default_db"
)
public class Discount implements java.io.Serializable {

    private Integer idDiscount;
    private String numcard;
    private String name;
    private String lastname;
    private String phone;
    private String email;
    private Date dateRegister;
    private Date dateUsed;
    private String percent;
    private String note;
    private BigDecimal sumChecks;
    private Set checkDiscounts = new HashSet(0);
    private String classId;
    private String objectId;
    private Long telegramIdChat;

    public Discount() {
    }

    public Discount(String numcard, Date dateRegister, Date dateUsed) {
        this.numcard = numcard;
        this.dateRegister = dateRegister;
        this.dateUsed = dateUsed;
    }

    public Discount(String numcard, String name, String lastname, String phone, String email, Date dateRegister, Date dateUsed, String percent, BigDecimal sumChecks, Set checkDiscounts) {
        this.numcard = numcard;
        this.name = name;
        this.lastname = lastname;
        this.phone = phone;
        this.email = email;
        this.dateRegister = dateRegister;
        this.dateUsed = dateUsed;
        this.percent = percent;
        this.sumChecks = sumChecks;
        this.checkDiscounts = checkDiscounts;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_discount", unique = true, nullable = false)
    public Integer getIdDiscount() {
        return this.idDiscount;
    }

    public void setIdDiscount(Integer idDiscount) {
        this.idDiscount = idDiscount;
    }

    @NotEmpty(message = "Введите номер карты")
    @Column(name = "numcard", nullable = false, length = 50)
    public String getNumcard() {
        return this.numcard;
    }

    public void setNumcard(String numcard) {
        this.numcard = numcard;
    }

    @NotEmpty(message = "Имя должно быть задано")
    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "lastname", length = 50)
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Pattern(regexp = "(\\+\\d{11}|\\+\\d{12})+$", message = "Не правильно введен номер телефона")
    @Column(name = "phone", length = 50)
    @NotEmpty(message = "Номер телефона должен быть задан")
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Pattern(regexp = "^(?:[a-zA-Z0-9_'^&/+-])+(?:\\.(?:[a-zA-Z0-9_'^&/+-])+)"
            + "*@(?:(?:\\[?(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\\.)"
            + "{3}(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\]?)|(?:[a-zA-Z0-9-]+\\.)"
            + "+(?:[a-zA-Z]){2,}\\.?)$", message = "Не правильный E-mail!")
    @Column(name = "email", length = 50)
    @NotEmpty(message = "Почта должна быть задана")
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_register", nullable = false, length = 19)
    public Date getDateRegister() {
        return this.dateRegister;
    }

    public void setDateRegister(Date dateRegister) {
        this.dateRegister = dateRegister;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_used", nullable = false, length = 19)
    public Date getDateUsed() {
        return this.dateUsed;
    }

    public void setDateUsed(Date dateUsed) {
        this.dateUsed = dateUsed;
    }

    @NotEmpty(message = "Введите скидку в процентах")
    @Column(name = "percent", length = 50)
    public String getPercent() {
        return this.percent;
    }

    public void setPercent(String percent) {
        this.percent = percent;
    }

    @Column(name = "sum_checks", precision = 9)
    public BigDecimal getSumChecks() {
        return this.sumChecks;
    }

    public void setSumChecks(BigDecimal sumChecks) {
        this.sumChecks = sumChecks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "discount")
    public Set getCheckDiscounts() {
        return this.checkDiscounts;
    }

    public void setCheckDiscounts(Set checkDiscounts) {
        this.checkDiscounts = checkDiscounts;
    }

    @Column(name = "classId", length = 500)
    public String getClassId() {
        return classId;
    }

    public void setClassId(String classId) {
        this.classId = classId;
    }

    @Column(name = "objectId", length = 500)
    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    @Column(name = "note", length = 1000)
    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public Long getTelegramIdChat() {
        return telegramIdChat;
    }

    public void setTelegramIdChat(Long telegramIdChat) {
        this.telegramIdChat = telegramIdChat;
    }
    
    
}
