package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArrivalList generated by hbm2java
 */
@Entity
@Table(name = "dish",
        catalog = "default_db"
)
public class Dish implements java.io.Serializable {

    private Long idDish;
    private String name;
    private String code;
    private BigDecimal weight;
    private BigDecimal priceOpt;
    private CategoryDish categoryDish;
    @JsonIgnore
    private Set arrivalDishLists = new HashSet(0);

    public Dish() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_dish", unique = true, nullable = false)
    public Long getIdDish() {
        return idDish;
    }

    public void setIdDish(Long idDish) {
        this.idDish = idDish;
    }

    @Column(name = "name", nullable = false, length = 1000)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "code", nullable = false, length = 50)
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "weight", precision = 7, scale = 3)
    public BigDecimal getWeight() {
        return weight;
    }

    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    @Column(name = "priceOpt", precision = 9, scale = 2)
    public BigDecimal getPriceOpt() {
        return priceOpt;
    }

    public void setPriceOpt(BigDecimal priceOpt) {
        this.priceOpt = priceOpt;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_categorydish", nullable = false)
    public CategoryDish getCategoryDish() {
        return this.categoryDish;
    }

    public void setCategoryDish(CategoryDish categoryDish) {
        this.categoryDish = categoryDish;
    }
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dish")
    public Set getArrivalDishLists() {
        return this.arrivalDishLists;
    }

    public void setArrivalDishLists(Set arrivalDishLists) {
        this.arrivalDishLists = arrivalDishLists;
    }

}
