package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * GoodsAccounting generated by hbm2java
 */
public class GoodsAccountingForJson implements java.io.Serializable {

    private Long idGoodsAccounting;
    private String name;
    private String code;
    private BigDecimal price;
    private Date date;
    private Boolean checkin;
    private BigDecimal residueNew;
    private BigDecimal residueDiff;

    public GoodsAccountingForJson() {
    }

    public Long getIdGoodsAccounting() {
        return idGoodsAccounting;
    }

    public void setIdGoodsAccounting(Long idGoodsAccounting) {
        this.idGoodsAccounting = idGoodsAccounting;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Boolean getCheckin() {
        return checkin;
    }

    public void setCheckin(Boolean checkin) {
        this.checkin = checkin;
    }

    public BigDecimal getResidueNew() {
        return residueNew;
    }

    public void setResidueNew(BigDecimal residueNew) {
        this.residueNew = residueNew;
    }

    public BigDecimal getResidueDiff() {
        return residueDiff;
    }

    public void setResidueDiff(BigDecimal residueDiff) {
        this.residueDiff = residueDiff;
    }

 

}
