package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonView;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Goods generated by hbm2java
 */
@Entity
@Table(name = "goods",
        catalog = "default_db"
)
@JsonPropertyOrder({"idGoods", "name", "code", "residue", "price", "priceOpt", "marking"})
public class Goods implements java.io.Serializable {

    @JsonView(ml.model.CheckList.class)
    private Long idGoods;
    @JsonIgnore
    private CategoryGoods categoryGoods;
    @JsonIgnore
    private String name;
    private String code;
    @JsonIgnore
    private BigDecimal residue;
    @JsonIgnore
    private BigDecimal price;
    @JsonIgnore
    private BigDecimal priceOpt;
    @JsonIgnore
    private Date date;
    private Boolean marking;
    @JsonIgnore
    private Set writeoffLists = new HashSet(0);
    @JsonIgnore
    private Set goodsAccountings = new HashSet(0);
    @JsonIgnore
    private Set arrivalLists = new HashSet(0);
    @JsonIgnore
    private Set checkLists = new HashSet(0);
    @JsonIgnore
    private Set barcodes = new HashSet(0);
    @JsonIgnore
    private Set reportsAccountings = new HashSet(0);
    @JsonIgnore
    private Set favorite = new HashSet(0);

    public Goods() {
    }

    public Goods(CategoryGoods categoryGoods, String name, String code) {
        this.categoryGoods = categoryGoods;
        this.name = name;
        this.code = code;
    }

    public Goods(CategoryGoods categoryGoods, String name, String code, BigDecimal residue, BigDecimal price,
            BigDecimal priceOpt, Date date, Set writeoffLists, Set goodsAccountings,
            Set arrivalLists, Set checkLists, Set barcodes, Set reportsAccountings) {
        this.categoryGoods = categoryGoods;
        this.name = name;
        this.code = code;
        this.residue = residue;
        this.price = price;
        this.priceOpt = priceOpt;
        this.date = date;
        this.writeoffLists = writeoffLists;
        this.goodsAccountings = goodsAccountings;
        this.arrivalLists = arrivalLists;
        this.checkLists = checkLists;
        this.barcodes = barcodes;
        this.reportsAccountings = reportsAccountings;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_goods", unique = true, nullable = false)
    public Long getIdGoods() {
        return this.idGoods;
    }

    public void setIdGoods(Long idGoods) {
        this.idGoods = idGoods;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_categoryGoods", nullable = false)
    public CategoryGoods getCategoryGoods() {
        return this.categoryGoods;
    }

    public void setCategoryGoods(CategoryGoods categoryGoods) {
        this.categoryGoods = categoryGoods;
    }

    @Column(name = "name", nullable = false, length = 500)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "code", unique = true, nullable = false, length = 50)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "residue", precision = 7, scale = 3)
    public BigDecimal getResidue() {
        return this.residue;
    }

    public void setResidue(BigDecimal residue) {
        this.residue = residue;
    }

    @Column(name = "price", precision = 9)
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Column(name = "price_opt", precision = 9)
    public BigDecimal getPriceOpt() {
        return this.priceOpt;
    }

    public void setPriceOpt(BigDecimal priceOpt) {
        this.priceOpt = priceOpt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "marking")
    public Boolean getMarking() {
        return marking;
    }

    public void setMarking(Boolean marking) {
        this.marking = marking;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
    public Set getWriteoffLists() {
        return this.writeoffLists;
    }

    public void setWriteoffLists(Set writeoffLists) {
        this.writeoffLists = writeoffLists;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
    public Set getGoodsAccountings() {
        return this.goodsAccountings;
    }

    public void setGoodsAccountings(Set goodsAccountings) {
        this.goodsAccountings = goodsAccountings;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
    public Set getArrivalLists() {
        return this.arrivalLists;
    }

    public void setArrivalLists(Set arrivalLists) {
        this.arrivalLists = arrivalLists;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
    public Set getCheckLists() {
        return this.checkLists;
    }

    public void setCheckLists(Set checkLists) {
        this.checkLists = checkLists;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
    public Set getBarcodes() {
        return this.barcodes;
    }

    public void setBarcodes(Set barcodes) {
        this.barcodes = barcodes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
    public Set getReportsAccountings() {
        return this.reportsAccountings;
    }

    public void setReportsAccountings(Set reportsAccountings) {
        this.reportsAccountings = reportsAccountings;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
    public Set getFavorite() {
        return this.favorite;
    }

    public void setFavorite(Set favorite) {
        this.favorite = favorite;
    }

}
