package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

/**
 * GoodsAccounting generated by hbm2java
 */
public class GoodsLoadForJson implements java.io.Serializable {

    private String code;
    private String residue;

    public GoodsLoadForJson() {
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getResidue() {
        return residue;
    }

    public void setResidue(String residue) {
        this.residue = residue;
    }

}
