package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.apache.log4j.Logger;

/**
 * Check generated by hbm2java
 */
@Entity
@Table(name = "log",
        catalog = "default_db"
)
public class Log implements java.io.Serializable {

    private Logger l;

    private Integer idlog;
    private Date date;
    private String level;
    private String logger;
    private String mdefault_dbge;

    public Log() {
    }

    public Log(Integer idlog, Date date, String level, String logger, String mdefault_dbge) {
        this.idlog = idlog;
        this.date = date;
        this.level = level;
        this.logger = logger;
        this.mdefault_dbge = mdefault_dbge;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idlog", unique = true, nullable = false)
    public Integer getidlog() {
        return idlog;
    }

    public void setidlog(Integer idlog) {
        this.idlog = idlog;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "level", length = 100)
    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    @Column(name = "logger", length = 500)
    public String getLogger() {
        return logger;
    }

    public void setLogger(String logger) {
        this.logger = logger;
    }

    @Column(name = "mdefault_dbge", length = 500)
    public String getMdefault_dbge() {
        return mdefault_dbge;
    }

    public void setMdefault_dbge(String mdefault_dbge) {
        this.mdefault_dbge = mdefault_dbge;
    }

    public Logger getL() {
        return l;
    }

    public void setL(Logger l) {
        this.l = l;
    }

}
