package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArrivalList generated by hbm2java
 */
@Entity
@Table(name = "techmap",
        catalog = "default_db"
)
public class TechMap implements java.io.Serializable {

    private Long idTechMap;
    private Goods goods;
    private Dish dish;
    private BigDecimal gross;

    public TechMap() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_techmap", unique = true, nullable = false)
    public Long getIdTechMap() {
        return idTechMap;
    }

    public void setIdTechMap(Long idTechMap) {
        this.idTechMap = idTechMap;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_goods", nullable = false)
    public Goods getGoods() {
        return this.goods;
    }

    public void setGoods(Goods goods) {
        this.goods = goods;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_dish", nullable = false)
    public Dish getDish() {
        return this.dish;
    }

    public void setDish(Dish dish) {
        this.dish = dish;
    }

    @Column(name = "price", precision = 7, scale = 3)
    public BigDecimal getGross() {
        return gross;
    }

    public void setGross(BigDecimal gross) {
        this.gross = gross;
    }
}
